# Generated by Django 5.0.2 on 2024-02-27 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='trending',
            field=models.BooleanField(default=False, help_text='1-show 0-hidden'),
        ),
        migrations.AddField(
            model_name='theme',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
