# Generated by Django 5.0.2 on 2024-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0003_alter_movie_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
