# Generated by Django 5.0.2 on 2024-03-03 11:53

import hrzflix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0007_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('movie_image', models.ImageField(upload_to=hrzflix.models.getfilename)),
                ('description', models.CharField(help_text='Note give only 80 Letters', max_length=80)),
                ('rating', models.FloatField()),
                ('duration', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
