# Generated by Django 5.0.2 on 2024-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0009_alter_slider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(help_text='Note give only 80 Letters', max_length=81),
        ),
    ]
