# Generated by Django 5.0.2 on 2024-03-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0010_alter_slider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrzflix.theme'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
