# Generated by Django 5.0.2 on 2024-03-03 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0011_slider_theme_alter_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrzflix.movie'),
        ),
    ]
