# Generated by Django 5.0.2 on 2024-03-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0012_slider_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrzflix.movie'),
        ),
    ]
