# Generated by Django 5.0.2 on 2024-03-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0013_alter_slider_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='movies',
        ),
    ]
