# Generated by Django 5.0.2 on 2024-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0014_remove_slider_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(default='https://youtu.be/TcMBFSGVi1c?si=czodo3KRTSWrj2U-', max_length=100),
        ),
    ]
