# Generated by Django 5.0.2 on 2024-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0015_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='trailer_url',
            field=models.URLField(default='https://youtu.be/TcMBFSGVi1c?si=czodo3KRTSWrj2U-', max_length=100),
        ),
    ]
