# Generated by Django 5.0.2 on 2024-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrzflix', '0017_alter_slider_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='https://youtu.be/TcMBFSGVi1c?si=czodo3KRTSWrj2U-', max_length=100, null=True),
        ),
    ]
